services:
  db-lm:
    build: conf/pgsql
    restart: always
    user: root
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./conf/pgsql/db-data:/var/lib/postgresql/data
      - ./conf/pgsql/postgres.conf:/etc/postgresql/postgresql.conf
  db-lm-test:
    build: conf/pgsql
    restart: always
    user: root
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
  nginx-lm:
    image: nginx:1.21.4-alpine
    volumes:
      - ../:/var/www
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ../storage/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - lm
  lm:
    build: conf/php
    restart: always
    expose:
      - 6001
    volumes:
      - ..:/var/www
    depends_on:
      - db-lm
      - db-test
      - redis
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
  redis-lm:
    build: conf/redis
    restart: always
    expose:
      - 6379
    volumes:
      - ./conf/redis/db-data:/data
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
  adminer-lm:
    build: conf/adminer
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
      - ADMINER_DEFAULT_USER=${DB_USERNAME}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /sessions
    depends_on:
      - db-lm
